/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Fail-loud stub floor for src/rccl_wrap.cc's host-only microtest, compiled
// into rccl-UnitTestsMicro alongside p2p.cc/rma_proxy_progress.cc's own
// tests. #include-ing the whole 1771-line rccl_wrap.cc (via WRAP_CC_PATH)
// pulls in the DDA / CE / symmetric-kernel / hierarchical backend-selection
// machinery even though the current test batch only exercises a handful of
// low-dependency helpers at the top of the file (see wrap-test.cc).
// Everything below satisfies the link closure; entries the current tests
// never reach default to abort()-on-call so an accidentally exercised path
// fails fast instead of silently returning a wrong answer.
//
// Deliberately NOT reusing nccl_stubs.cc / bootstrap_stubs.cc / topo_stubs.cc
// / transport_stubs.cc here: those are curated for init.cc and each already
// stubs commSetUnrollFactor and rcclCommSetP2pShiftSize as abort() floors for
// init.cc's benefit -- both are REAL functions defined by rccl_wrap.cc
// itself, so linking those files together with this one would be a
// duplicate-symbol error. fakes/nccl_fakes.cc (p2p.cc's fakes, already part
// of this binary) has no such conflict -- p2p.cc never calls either function
// -- so this file's logging globals (below) are shared with nccl_fakes.cc's
// rather than duplicated.
//
// RCCL_PARAM / NCCL_PARAM: every RCCL_PARAM(...) invocation textually inside
// rccl_wrap.cc is redirected by wrap-test.cc to return its compile-time
// default directly (no test in the current batch needs a specific param
// value, so there is nothing yet to make per-test-controllable -- see
// wrap-test.cc's redirector comment for the upgrade path) and needs no stub
// here. The few ncclParamXxx / rcclParamXxx symbols rccl_wrap.cc declares
// `extern` and calls without a local RCCL_PARAM/NCCL_PARAM invocation (their
// generator lives in another .cc) are stubbed below instead.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "nccl.h"
#include "comm.h"
#include "debug.h"
#include "rccl_common.h"
#include "enqueue.h"     // NCCL_ALGO_*/NCCL_PROTO_*, ncclSimInfo_t (getAlgoInfo's param)
#include "group.h"
#include "ce_coll.h"
#include "sym_kernels.h"
#include "dev_runtime.h"
#include "strongstream.h"
#include "algorithms/dda/all_reduce/dda_all_reduce.h"
#include "algorithms/dda/all_gather/dda_all_gather.h"
#include "algorithms/dda/reduce_scatter/dda_reduce_scatter.h"
#include "amdsmi_wrap.h"

// ---------------------------------------------------------------------------
// Logging infrastructure. WARN/INFO (debug.h) expand to ncclDebugLog(); three
// of the current Tier-1 units (rcclGetAlgoProtoIndex, rcclGetAlgoName,
// rcclGetProtocolName) call WARN on their invalid-input arms, and tests assert
// on that text via gtest's stderr capture.
//
// ncclDebugLevel / ncclDebugMask / ncclDebugNoWarn / ncclDebugLog() itself
// are defined once, by fakes/nccl_fakes.cc, which this binary already links
// for p2p.cc's tests -- defining them again here would be a duplicate-symbol
// error. ncclDebugMask's default there (0) differs from what this file used
// when it was its own standalone binary (~0ULL), but that's not observable
// by anything currently covered: WARN(...) calls ncclDebugLog() unconditionally
// regardless of mask, and no function covered so far calls INFO(...) (which
// does check ncclDebugLevel/ncclDebugMask) at all. A future test that needs to
// capture an INFO(...) line should raise both explicitly first, e.g. with
// RcclUnitTesting::ScopedDebugLogging, rather than relying on either side's
// default.
// ---------------------------------------------------------------------------
FILE* ncclDebugFile = nullptr;
char  ncclLastError[1024] = {};

// ---------------------------------------------------------------------------
// ncclParamXxx / rcclParamXxx symbols NOT generated by an RCCL_PARAM/NCCL_PARAM
// invocation inside rccl_wrap.cc itself (see file header comment). Trivial
// real behaviour (return the production default) rather than abort(): these
// are read on essentially every call into the file's channel/DDA tuning
// paths, so an abort-floor here would make even unrelated tests crash before
// reaching the function they actually meant to exercise.
//
// Unlike NCCL_NUM_ALGORITHMS/ncclNumFuncs above, there's no importable
// constant for "the current default" here -- NCCL_PARAM/RCCL_PARAM bakes
// deftVal directly as an inline macro-argument literal (see param.h), not a
// separately declared symbol, so a static_assert can't check it. Instead,
// wrap-test.cc's ParamDefaults_MatchProductionSource test reads the real
// graph/connect.cc / enqueue.cc source at run time and confirms the exact
// NCCL_PARAM/RCCL_PARAM(...) invocation text below still matches -- a
// run-time tripwire where a compile-time one isn't possible.
// ---------------------------------------------------------------------------
int64_t ncclParamMinNchannels() { return -2; }              // graph/connect.cc:832
int64_t ncclParamMaxNchannels() { return -2; }              // graph/connect.cc:833
int64_t rcclParamForceCe() { return 1; }                    // enqueue.cc:3785
int64_t ncclParamLaunchOrderImplicit() { return 0; }        // enqueue.cc:1985

// ncclGetEnv: real signature returns nullptr for an unset var. No test in the
// current batch reads an env var through this path (rcclOverrideProtocol /
// rcclOverrideAlgorithm / rcclUseAllGatherDirect are out of scope here);
// default to "unset" so RCCL_OVERRIDE_PROTO-style static-once guards stay on
// their no-override arm until a future test batch adds a controllable seam.
const char* ncclGetEnv(const char* /*name*/) { return nullptr; }

// ncclDevFuncUnrollGenerated: extern bool const[NCCL_NUM_UNROLLS]. Real array,
// not abort-floor -- commSetUnrollFactor indexes it unconditionally on every
// call, including the manual-override path any Tier-1-adjacent test might
// exercise. All-true is the safe default: "every unroll factor was built".
//
// The static_assert below is the same signature-drift-watchdog idea as
// fakes/signature-drift.h: without it, a new unroll factor added to RCCL
// wouldn't fail to compile here -- the extra array slot would just silently
// zero-initialize to false, quietly changing behavior instead of erroring.
static_assert(NCCL_NUM_UNROLLS == 6,
              "NCCL_NUM_UNROLLS changed -- add/remove a `true` entry below to match");
const bool ncclDevFuncUnrollGenerated[NCCL_NUM_UNROLLS] = {true, true, true, true, true, true};

// ncclCommCount: trivial accessor, real behaviour costs nothing and de-risks
// future test batches (rcclGetAlgoInfo reads it via NCCLCHECK(ncclCommCount(...))).
ncclResult_t ncclCommCount(const ncclComm_t comm, int* count) {
  if (count) *count = comm ? comm->nRanks : 0;
  return ncclSuccess;
}

// ---------------------------------------------------------------------------
// ncclAlgoToString / ncclProtoToString / ncclFuncToString / ncclDatatypeToString:
// faithful copies of collectives.cc's trivial switch tables, NOT abort-floors
// -- rcclGetAlgoName/rcclGetProtocolName (Tier-1, tested below) delegate to
// the first two for native algo/protocol values, and rcclOverrideProtocol/
// rcclOverrideAlgorithm (out of scope here) use all four in WARN messages. Real
// collectives.cc is not linked here: it pulls in the DDA/symmetric-kernel/
// nvtx dependency chain this lean binary otherwise avoids entirely (see the
// file header comment). Each function below names the exact definition it
// copies, so a drift is checkable without leaving this file.
//
// NCCL_ALGO_* / NCCL_PROTO_* are plain #defines, not a real enum, so the
// compiler can't warn on a switch missing a newly-added case the way it could
// for an enum. The counts below are the same signature-drift-watchdog idea as
// fakes/signature-drift.h (a build-time tripwire instead of a human noticing
// a stale comment): if RCCL ever adds/removes an algorithm or protocol, this
// static_assert breaks the build right here, forcing the switches below to be
// updated to match, rather than silently returning "Unknown".
static_assert(NCCL_NUM_ALGORITHMS == 7,
              "NCCL_NUM_ALGORITHMS changed -- update ncclAlgoToString's switch below to match collectives.cc:115");
static_assert(NCCL_NUM_PROTOCOLS == 3,
              "NCCL_NUM_PROTOCOLS changed -- update ncclProtoToString's switch below to match collectives.cc:136");
//
// ncclFunc_t / ncclDataType_t ARE real enums, each with its own trailing
// count sentinel (ncclNumFuncs, ncclNumTypes -- nccl_common.h / nccl.h.in),
// so unlike NCCL_ALGO_*/NCCL_PROTO_* there's a real symbol to check here too.
static_assert(ncclNumFuncs == 19,
              "ncclFunc_t changed -- update ncclFuncToString's switch below to match collectives.cc:32");
static_assert(ncclNumTypes == 12,
              "ncclDataType_t changed -- update ncclDatatypeToString's switch below to match collectives.cc:86");
// ---------------------------------------------------------------------------
const char* ncclFuncToString(ncclFunc_t fn) {  // collectives.cc:32
  switch (fn) {
  case ncclFuncAllGather: return "AllGather";
  case ncclFuncAllReduce: return "AllReduce";
  case ncclFuncAlltoAll: return "AlltoAll";
  case ncclFuncAlltoAllv: return "AlltoAllv";
  case ncclFuncBroadcast: return "Broadcast";
  case ncclFuncGather: return "Gather";
  case ncclFuncRecv: return "Recv";
  case ncclFuncReduce: return "Reduce";
  case ncclFuncReduceScatter: return "ReduceScatter";
  case ncclFuncScatter: return "Scatter";
  case ncclFuncSendRecv: return "SendRecv";
  case ncclFuncSend: return "Send";
  case ncclFuncPutSignal: return "PutSignal";
  case ncclFuncSignal: return "Signal";
  case ncclFuncWaitSignal: return "WaitSignal";
  default: return "Invalid";
  }
}

const char* ncclDatatypeToString(ncclDataType_t type) {  // collectives.cc:86
  switch (type) {
  case ncclInt8: return "ncclInt8";
  case ncclInt32: return "ncclInt32";
  case ncclUint32: return "ncclUint32";
  case ncclInt64: return "ncclInt64";
  case ncclUint64: return "ncclUint64";
  case ncclFloat16: return "ncclFloat16";
  case ncclFloat32: return "ncclFloat32";
  case ncclFloat64: return "ncclFloat64";
  case ncclBfloat16: return "ncclBfloat16";
  case ncclFloat8e4m3: return "ncclFloat8e4m3";
  case ncclFloat8e5m2: return "ncclFloat8e5m2";
  default: return "Unknown";
  }
}

const char* ncclAlgoToString(int algo) {  // collectives.cc:115
  switch (algo) {
  case NCCL_ALGO_TREE: return "TREE";
  case NCCL_ALGO_RING: return "RING";
  case NCCL_ALGO_COLLNET_DIRECT: return "COLLNET_DIRECT";
  case NCCL_ALGO_COLLNET_CHAIN: return "COLLNET_CHAIN";
  case NCCL_ALGO_NVLS: return "NVLS";
  case NCCL_ALGO_NVLS_TREE: return "NVLS_TREE";
  case NCCL_ALGO_PAT: return "PAT";
  default: return "Unknown";
  }
}

const char* ncclProtoToString(int proto) {  // collectives.cc:136
  switch (proto) {
  case NCCL_PROTO_LL: return "LL";
  case NCCL_PROTO_LL128: return "LL128";
  case NCCL_PROTO_SIMPLE: return "SIMPLE";
  default: return "Unknown";
  }
}

// ---------------------------------------------------------------------------
// Abort floor: reachable only from rcclSelectAllReduce / rcclSelectAllGather /
// rcclSelectReduceScatter / rcclHierarchicalAlgoInfo / rcclGetAlgoInfo /
// rcclSymKGetInfo -- none exercised by the current test batch. Kept as
// abort() so a test that accidentally reaches one of these fails immediately
// at the exact call site instead of silently taking a wrong default; upgrade
// to a controllable seam the moment a future test needs to drive one of
// these -- see MICROTEST_README.md, "Adding more controllable seams."
// ---------------------------------------------------------------------------

bool isSymmetricKernelRequested(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*, void*) {
  ::abort();
}

ncclResult_t ncclCudaGetCapturingGraph(struct ncclCudaGraph*, hipStream_t, int) { ::abort(); }

ncclResult_t ncclDevrFindWindow(struct ncclComm*, void const*, struct ncclDevrWindow**) { ::abort(); }
bool ncclDevrWindowHasSysmemSegment(struct ncclDevrWindow*) { ::abort(); }
ncclResult_t ncclGetSymRegType(struct ncclDevrWindow*, struct ncclDevrWindow*, ncclSymRegType_t*) { ::abort(); }

ncclResult_t ncclSymkInitOnce(struct ncclComm*) { ::abort(); }
bool ncclSymkAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t) { ::abort(); }
ncclResult_t ncclSymkPickKernel(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, size_t, int,
                                ncclSymRegType_t, float*, ncclSymkKernelId*, int*, int*, bool*) {
  ::abort();
}
bool rcclSymkKernelIdIsLL(int) { ::abort(); }

bool ncclCeAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t) { ::abort(); }
bool ncclCeScratchAvailable(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, ncclSymRegType_t) { ::abort(); }
int ncclCeLocalReduceBlocks(ncclDataType_t, size_t) { ::abort(); }

bool rcclAllReduceShouldTakeDdaPath(struct ncclComm*, size_t, ncclDataType_t, bool, bool) { ::abort(); }

// getAlgoInfo / rcclKernelPackedChannels: rccl_wrap.cc `extern`-declares both
// itself (their real definitions live in enqueue.cc / device-side tuning,
// outside this TU's link closure), so no separate declaration is needed here.
ncclResult_t getAlgoInfo(struct ncclComm*, struct ncclTaskColl*, int, int, int, ncclSimInfo_t*) { ::abort(); }
int rcclKernelPackedChannels(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int) { ::abort(); }

// rcclLL128ElemsPerThreadFromArch is `inline` in archinfo.h (transitively
// included), so no stub is needed here.

// getFirmwareVersion()'s sole dependency; getFirmwareVersion() itself is not
// in the current test batch (Structural: needs a mock AMD-SMI response, not
// just a comm/task struct -- a future test's seam, not an abort-floor gap).
ncclResult_t amd_smi_getFirmwareVersion(uint32_t, uint64_t*) { ::abort(); }

// --- AllReduce DDA (dda_all_reduce.h) ---
bool ncclAllReduceDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) { ::abort(); }
bool ncclAllReduceDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) { ::abort(); }
bool ncclAllReduceDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) { ::abort(); }
bool ncclAllReduceDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  ::abort();
}
uint32_t ncclAllReduceDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllReduceDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllReduceDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllReduceDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }

// --- AllGather DDA (dda_all_gather.h) ---
bool ncclAllGatherDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { ::abort(); }
bool ncclAllGatherDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { ::abort(); }
bool ncclAllGatherDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { ::abort(); }
bool ncclAllGatherDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllGatherDdaIpcBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllGatherDdaFabricBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllGatherDdaFabricLLBlocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }
uint32_t ncclAllGatherDdaFabricLL128Blocks(ncclComm*, size_t, ncclDataType_t) { ::abort(); }

// --- ReduceScatter DDA (dda_reduce_scatter.h) ---
bool ncclReduceScatterDdaIpcEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  ::abort();
}
bool ncclReduceScatterDdaFabricEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  ::abort();
}
bool ncclReduceScatterDdaFabricLLEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  ::abort();
}
bool ncclReduceScatterDdaFabricLL128Eligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  ::abort();
}
