#!/usr/bin/env python3
# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT
"""Check that AMD-owned source files carry the standard SPDX MIT header.

Check-only: reports files missing or with a malformed header and exits 1. It
never edits files. Wired in as a pre-commit hook so drift from the two-line
header convention (see .github/CONTRIBUTING.md) is caught before it lands.

The expected header, using the file's comment leader, is:

    <c> Copyright Advanced Micro Devices, Inc.
    <c> SPDX-License-Identifier: MIT

where <c> is ``//`` for C/C++/Go/Rust and ``#`` for Python/CMake/shell.

Third-party, vendored, and generated files are out of scope (see EXCLUDE_*).

Run manually:

    python3 projects/amdsmi/tests/check_license_headers.py            # scan tree
    python3 projects/amdsmi/tests/check_license_headers.py FILE...    # check given
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve()
PROJECT_ROOT = HERE.parents[1]  # projects/amdsmi
REPO_ROOT = HERE.parents[3]  # rocm-systems

COPYRIGHT_LINE = "Copyright Advanced Micro Devices, Inc."
SPDX_LINE = "SPDX-License-Identifier: MIT"

# --------------------------------------------------------------------------- #
# Scope — which files must carry the header.
# --------------------------------------------------------------------------- #

_C_EXT = {".h", ".hh", ".hpp", ".hxx", ".c", ".cc", ".cpp", ".cxx", ".cu", ".inc"}
SLASH_EXT = _C_EXT | {".go", ".rs"}  # // comment leader
HASH_EXT = {".py", ".cmake", ".sh"}  # # comment leader
HASH_BASE = {"CMakeLists.txt", "Makefile"}

# Skipped entirely: different copyright owner, vendored upstream, generated, or
# the license texts themselves.
EXCLUDE_PREFIX = (
    "third_party/",  # vendored (shared_mutex, Oleg Yamnikov)
    "esmi_ib_library/",  # vendored E-SMI, own COPYING/License.txt
    "build/",
    "docs/",
    "include/libdrm/",  # vendored DRM headers, other owners
    "src/nic/brcm-nic/",  # Broadcom-owned NIC implementation
    "include/ras-decode/",  # vendored RAS decode headers, not maintained here
    # Vendored UALoE library, not maintained here -- both halves are replaced
    # wholesale by the periodic "sync UALoE lib" drops, so a header rewritten
    # here is reverted by the next sync. Matches the `ualoe_lib/` entry that
    # keeps the rest of the pre-commit suite off this code.
    "include/ualoe_lib/",
    "src/ualoe_lib/",
    # Agent tooling, not shipped source: nothing under here is compiled,
    # installed or distributed, so the header convention does not apply.
    ".claude/",
)
EXCLUDE_EXACT = frozenset(
    {
        "py-interface/amdsmi_wrapper.py",  # generated by tools/generator.py
        "rust-interface/src/amdsmi_wrapper.rs",  # generated by rust-bindgen
        "include/amd_smi/impl/amd_hsmp.h",  # Linux kernel UAPI, GPL-2.0
        "include/amd_smi/impl/xf86drm.h",  # X.Org
        # Broadcom-owned NIC headers (counterparts to src/nic/brcm-nic/).
        "include/amd_smi/impl/nic/amd_smi_lspci_commands.h",
        "include/amd_smi/impl/nic/amd_smi_nic_device.h",
        "include/amd_smi/impl/nic/amd_smi_no_drm_nic.h",
        "include/amd_smi/impl/nic/amd_smi_no_drm_switch.h",
        "include/amd_smi/impl/nic/amd_smi_switch_device.h",
    }
)


def base_ext(rel: str) -> tuple[str, str]:
    """(extension, basename) for ``rel``.

    ``.in`` build templates keep their ``.in`` extension, so they are not
    recognized as a source language and fall out of scope.
    """
    return os.path.splitext(rel)[1], os.path.basename(rel)


def comment_leader(rel: str) -> str | None:
    """Comment leader for the file's language, or None if not in a source language."""
    ext, base = base_ext(rel)
    if ext in SLASH_EXT:
        return "//"
    if ext in HASH_EXT or base in HASH_BASE:
        return "#"
    return None


def is_excluded(rel: str) -> bool:
    if rel in EXCLUDE_EXACT:
        return True
    if rel.startswith(EXCLUDE_PREFIX):
        return True
    base = os.path.basename(rel)
    if base.startswith(("LICENSE", "COPYING")):
        return True
    return rel.endswith((".md", ".rst"))


def in_scope(rel: str) -> bool:
    return comment_leader(rel) is not None and not is_excluded(rel)


def is_trivial(text: str, leader: str) -> bool:
    """A file with no real code — only blank/comment lines (e.g. empty __init__.py)."""
    starts = ("//", "/*", "*") if leader == "//" else ("#",)
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith(starts):
            return False
    return True


def has_header(text: str) -> bool:
    head = "\n".join(text.splitlines()[:15])
    return COPYRIGHT_LINE in head and SPDX_LINE in head


def has_orphaned_block_tail(text: str, leader: str) -> bool:
    """A ``*/`` with no ``/*`` before it — debris from a half-replaced block header.

    The two SPDX lines can be present while the tail of the old comment survives,
    so presence alone does not mean the file still parses.
    """
    if leader != "//":
        return False
    head = text.splitlines()[:15]
    close = next((i for i, line in enumerate(head) if "*/" in line), None)
    if close is None:
        return False
    return not any("/*" in line for line in head[: close + 1])


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


def _tracked_files() -> list[str]:
    out = subprocess.check_output(["git", "-C", str(PROJECT_ROOT), "ls-files"])
    return out.decode().splitlines()


def _to_rel(arg: str) -> str | None:
    """Normalize a CLI/pre-commit path to a project-relative path, or None."""
    p = Path(arg)
    if not p.is_absolute():
        p = REPO_ROOT / arg if (REPO_ROOT / arg).exists() else PROJECT_ROOT / arg
    try:
        return str(p.resolve().relative_to(PROJECT_ROOT))
    except ValueError:
        return None


def main(argv: list[str]) -> int:
    rels = [r for r in (_to_rel(a) for a in argv) if r] if argv else _tracked_files()
    missing = []
    orphaned = []
    for rel in rels:
        if not in_scope(rel):
            continue
        path = PROJECT_ROOT / rel
        if not path.is_file():
            continue
        text = path.read_text(errors="replace")
        leader = comment_leader(rel)
        if is_trivial(text, leader):
            continue
        if not has_header(text):
            missing.append(rel)
        elif has_orphaned_block_tail(text, leader):
            orphaned.append(rel)
    if missing:
        print("Missing or malformed AMD SPDX license header:")
        for rel in sorted(missing):
            print(f"  {rel}")
        print("\nExpected near the top of the file (comment leader per language):")
        print(f"    {COPYRIGHT_LINE}")
        print(f"    {SPDX_LINE}")
    if orphaned:
        print("Leftover block-comment tail below the SPDX header ('*/' with no '/*'):")
        for rel in sorted(orphaned):
            print(f"  {rel}")
        print("\nDelete the remnant lines of the old license block.")
    return 1 if (missing or orphaned) else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
